services:
    image_sf.admin.image:
        class: ImageSFBundle\Admin\ImageAdmin
        arguments: [~, ImageSFBundle\Entity\Image, ImageSFBundle:ImageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ImageNew }

    image_sf.image_uploader:
            class: ImageSFBundle\ImageUploader\ImageUploader
            arguments: ['%images_directory%']

    image_sf.doctrine_image_listener:
            class: ImageSFBundle\EventListener\ImageUploadListener
            arguments: ['@image_sf.image_uploader']
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: postLoad }