<?php

namespace GarageBundle\Repository;

/**
 * NewCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewCarRepository extends \Doctrine\ORM\EntityRepository
{
}
