<?php

namespace GarageBundle\Repository;

/**
 * PartnershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnershipRepository extends \Doctrine\ORM\EntityRepository
{
}
