<?php

namespace GarageBundle\Repository;

/**
 * SecondHandCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondHandCarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithPromotion(){
        $qb = $this->createQueryBuilder('shc');
        $qb->add('where', $qb->expr()->isNotNull('shc.promotion'));

        return $qb
            ->getQuery()
            ->getResult();
    }
}
