<?php

namespace GarageBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithPromotion(){
        $qb = $this->createQueryBuilder('s');
        $qb->add('where', $qb->expr()->isNotNull('s.promotion'));

        return $qb
            ->getQuery()
            ->getResult();
    }
}
