services:
    app.admin.promotion:
        class: AppBundle\Admin\PromotionAdmin
        arguments: [~, AppBundle\Entity\Promotion, AppBundle:PromotionAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Promotion }

    app.admin.image:
        class: AppBundle\Admin\ImageAdmin
        arguments: [~, AppBundle\Entity\Image, AppBundle:ImageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Image }


    app.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, AppBundle:ArticleAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Articles }

    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, AppBundle:EmployeeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Employés }
