services:
    app.admin.promotion:
        class: AppBundle\Admin\PromotionAdmin
        arguments: [~, AppBundle\Entity\Promotion, AppBundle:PromotionAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: autres, label: Promotions }

    app.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, AppBundle:ArticleAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: autres, label: Articles }

    app.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, AppBundle:EmployeeAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: generale, label: Employés }

    app.admin.home_page:
        class: AppBundle\Admin\HomePageAdmin
        arguments: [~, AppBundle\Entity\HomePage, AppBundle:HomePageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: generale, label: Page d'accueil }
