services:
#    garage.example:
#        class: GarageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    garage.admin.garage:
        class: GarageBundle\Admin\GarageAdmin
        arguments: [~, GarageBundle\Entity\Garage, GarageBundle:GarageAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Le garage }

    garage.admin.service:
        class: GarageBundle\Admin\ServiceAdmin
        arguments: [~, GarageBundle\Entity\Service, GarageBundle:ServiceAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Prestations }
